/*
  Generating Random IDs
  - normally, id is generated by backend server

*/

import { useState } from 'react'
import BookCreate from './components/BookCreate'

function App() {
  const [books, setBooks] = useState([])

  const createBook = (title) => {
    // ***

    const updatedBooks = [
      ...books,
      // { id: Math.round(Math.random() * 9999), title },
      { id: new Date().getTime(), title }, // *** 2 ways to generate random id
    ]

    setBooks(updatedBooks)
  }

  return (
    <div>
      {books.length}
      <BookCreate onCreate={createBook} />
    </div>
  )
}

export default App
